package chain

type ErrCode int

//go:generate stringer -type ErrCode
const (
	ERR_UNSPECIFIED ErrCode		= 0
	ERR_DIFFERENT_CHAIN		= 1001
	ERR_ALREADY_CONNECTED		= 1002
	ERR_CONNECTED_TO_SELF		= 1003
	ERR_NOT_ACCEPTING_CONNECTIONS	= 1004
	ERR_BLOCKED			= 1005
	ERR_INVALID_HELLO_MESSAGE	= 1006
	ERR_CLIENT_TOO_OLD		= 1007

)

